logs:
  - name: root
    level: info
    formatter: '%d%T%m%n'
    appenders:
      - type: FileLogAppender
        level: error
        file: root.txt
      - type: StdoutLogAppender
        level: warn
  - name: system
    level: debug
    formatter: '%d%T%m%n'
    appenders:
      - type: FileLogAppender
        file: system.txt
      - type: StdoutLogAppender
